require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'colorized_string'
require 'pry'

require_relative './daily_trending/version'
require_relative  './daily_trending/app'
require_relative  './daily_trending/cli'
require_relative  './daily_trending/scraper'
