require 'nokogiri'
require 'open-uri'
require 'pry'
require 'colorize'
require 'colorized_string'
require 'elementor'

require_relative './daily_trending/version'
require_relative  './daily_trending/vid'
require_relative  './daily_trending/cli'
